---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rukpak-webhooks-admin
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
  - apiGroups:
      - core.rukpak.io
    resources:
      - bundles
    verbs:
      - list
      - watch
